package main

import (
	"fmt"
	"io"
	"log"
	"os"

	"github.com/alecthomas/kong"
	"github.com/winebarrel/json2go/v2"
)

var version string

func init() {
	log.SetFlags(0)
}

const (
	rootType = "AutoGenerated"
)

type options struct {
	File      string `arg:"" optional:"" help:"JSON file. If not specified, read from stdin."`
	Flat      bool   `negatable:"" help:"Flattening structs."`
	Omitempty bool   `negatable:"" default:"true" help:"Add 'omitempty' to optional fields. (default: true)"`
	Pointer   bool   `negatable:"" default:"true" help:"Make nullable fields pointer types. (default: true)"`
	RootType  bool   `negatable:"" default:"true" help:"Define root type. (default: true)"`
	Version   kong.VersionFlag
}

func parseArgs() *options {
	opts := &options{}
	parser := kong.Must(opts, kong.Vars{"version": version})
	parser.Model.HelpFlag.Help = "Show help."

	if _, err := parser.Parse(os.Args[1:]); err != nil {
		parser.FatalIfErrorf(err)
	}

	return opts
}

func main() {
	opts := parseArgs()
	var r io.Reader

	if opts.File == "" || opts.File == "-" {
		opts.File = "<stdin>"
		r = os.Stdin
	} else {
		file, err := os.Open(opts.File)

		if err != nil {
			log.Fatal(err)
		}

		defer file.Close()
		r = file
	}

	optfns := []json2go.OptFn{
		json2go.OptionFilename(opts.File),
		json2go.OptionFlat(opts.Flat),
		json2go.OptionOmitempty(opts.Omitempty),
		json2go.OptionPointer(opts.Pointer),
	}

	if opts.RootType {
		optfns = append(optfns, json2go.OptionRootType(rootType))
	}

	out, err := json2go.Convert(r, optfns...)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(string(out))
}
